#+TITLE: VagrantRDFCubes

* Introduction 
This repository provides all the necessary setup instructions to deploy a virtual machine setting up a conversion pipeline for statistical data. 
This work has been conducted by the Open Data Support project. See [[https://joinup.ec.europa.eu/community/ods/description][Open Data Support]]. 


This Vagrant description is for a virtualbox which runs ubuntu precise64.
It provides the 
- LodStatworkbench (accessible at http://localhost:8080/lod2statworkbench): see for more documentation http://wiki.lod2.eu/display/LOD2DOC/LOD2+Statistical+Workbench and the http://stack.linkeddata.org
- conversion tool-chain which converts the statistical data provided by the Cypriotic Statistical Office and the Bulgarian Statistical Office.

* Deployment steps
The deployment is also documented in the slides provided in the documentation.

** Vagrant installation

** activating the Vagrant machine description
  
  1. Vagrant installed
  2. check out the git repository
  3. startup vagrant
  4. login to the system
       user:vagrant/vagrant
       
       note credentials Virtuoso are dba/root

** Vagrant installation
  See https://www.vagrantup.com/
  Also install VirtualBox
   
*** Windows users
  Make 
*** Mac OS users

** GitHub support
  *** Windows users
  Install git-bash ()
  
#+BEGIN_SRC bash
  git clone <URI>
#+END_SRC
  

** Startup Vagrant
#+BEGIN_SRC bash
    # 
vagrant plugin install vagrant-vbguest
    # Which will install the virtualbox guest additions
    # allowing full screen for this virtualbox.
vagrant up
    # Which will make sure the interface is accessible
    # It will download the ISO image, and 
    # then will download all necessary packages
    # 
    # Estimated activation time depends on network download speed, but on a
    # high speed connection is approximately 15 minutes.
   
   # restart the system 
vagrant halt
vagrant up
#+END_SRC


