#+TITLE: VagrantRDFCubes

* Introduction 
This repository provides all the necessary setup instructions to
deploy a virtual machine setting up a conversion pipeline for
statistical data.  This work has been conducted as part of the [[https://joinup.ec.europa.eu/community/ods/description][Open
Data Support]] project.


This Vagrant machine description deploys a Ubuntu precise64.

It provides the 
- LodStatworkbench (accessible at
  http://localhost:8080/lod2statworkbench): see for more documentation
  http://wiki.lod2.eu/display/LOD2DOC/LOD2+Statistical+Workbench and
  the http://stack.linkeddata.org
- conversion tool-chain which converts the statistical data provided
  by the Cypriotic Statistical Office and the Bulgarian Statistical
  Office.

* Deployment steps
The deployment is also documented in the slides provided in the documentation.

** Prerequisites
- Vagrant [[https://www.vagrantup.com/]]
- VirtualBox [[https://www.virtualbox.org/]]
- git (for windows e.g. https://msysgit.github.io/)

** activating the Vagrant machine description
The high level process is as follows

  1. the prerequistes are full filled on the host environment
  2. check out the git repository
  3. initialize the virtual machine using Vagrant
  4. start the created virtual machine
  4. login to the system
       user:vagrant/vagrant
       
       note credentials Virtuoso are dba/root
** GitHub check out
  
#+BEGIN_SRC bash
  git clone <URI>
#+END_SRC
  
** Initialize the virtual machine using Vagrant
#+BEGIN_SRC bash
    # 
vagrant plugin install vagrant-vbguest
    # Which will install the virtualbox guest additions
    # allowing full screen for this virtualbox.
vagrant plugin install vagrant-cachier
    # Which will install a caching plugin to reduce network bandwidth requirements.
vagrant up
    # Which will make sure the interface is accessible
    # It will download the ISO image, and 
    # then will download all necessary packages
    # 
    # Estimated activation time depends on network download speed, but on a
    # high speed connection is approximately 15 minutes.
   
   # restart the system 
vagrant halt
vagrant up
#+END_SRC

More tips and tricks can be found in the slides.
